apiVersion: v1
kind: Namespace
metadata:
  name: cipher-x
  labels:
    app.kubernetes.io/name: cipher-x
    app.kubernetes.io/part-of: cipher-x-platform
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
