apiVersion: v1
kind: Secret
metadata:
  name: cipherx-secrets
  namespace: cipher-x
  labels:
    app.kubernetes.io/name: cipher-x
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "CipherXProductionPostgresPassword2026!"
  DATABASE_URL: "postgresql+asyncpg://cipherx:CipherXProductionPostgresPassword2026!@cipherx-db:5432/cipherx"
  SECRET_KEY: "prod-cipherx-super-secret-jwt-encryption-key-rotate-quarterly-2026"
  AI_API_KEY: ""
  MINIO_ROOT_USER: "cipherx_admin"
  MINIO_ROOT_PASSWORD: "CipherXSecureMinioProductionKey2026!"
