apiVersion: v1
kind: Service
metadata:
  name: cipherx-db
  namespace: cipher-x
  labels:
    app.kubernetes.io/name: cipher-x
    app.kubernetes.io/component: database
spec:
  ports:
    - port: 5432
      name: postgresql
  clusterIP: None
  selector:
    app.kubernetes.io/name: cipher-x
    app.kubernetes.io/component: database
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cipherx-db
  namespace: cipher-x
  labels:
    app.kubernetes.io/name: cipher-x
    app.kubernetes.io/component: database
spec:
  serviceName: cipherx-db
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cipher-x
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cipher-x
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
              name: postgresql
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: cipherx-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: cipherx-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cipherx-secrets
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2048Mi
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - cipherx
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - cipherx
            initialDelaySeconds: 5
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi
