apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cipherx-ingress
  namespace: cipher-x
  labels:
    app.kubernetes.io/name: cipher-x
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
    nginx.ingress.kubernetes.io/limit-rps: "50"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-XSS-Protection: 1; mode=block";
      more_set_headers "Strict-Transport-Security: max-age=31536000; includeSubDomains";
spec:
  tls:
    - hosts:
        - cipherx.enterprise.local
      secretName: cipherx-tls-cert
  rules:
    - host: cipherx.enterprise.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cipherx-frontend
                port:
                  number: 80
